## BaseNode — Exterior structure of the player's home base.
##
## Phase 6. Placed on the world map by HubWorld at L10 via
## BaseManager.place(hex, x, y). Visually grows and gets fancier per
## upgrade level (Phase 6: sprite_base + tier suffix). The exterior
## sprite is loaded by name; the per-tier sprite is procedurally
## generated by tools/generate_base_sprites.py.
class_name BaseNode
extends Node2D

const BASE_PATH := "/root/BaseManager"
const SCENE_PATH := "res://scenes/Base.tscn"

@export var base_data: Dictionary = {}

var _sprite: Sprite2D
var _label: Label
var _current_level: int = 1
var _placement: Dictionary = {}


func _ready() -> void:
	_sprite = get_node_or_null("Sprite") as Sprite2D
	if _sprite == null:
		_sprite = Sprite2D.new()
		_sprite.name = "Sprite"
		_sprite.centered = true
		add_child(_sprite)
	_label = get_node_or_null("Label") as Label
	if _label == null:
		_label = Label.new()
		_label.name = "Label"
		_label.add_theme_color_override("font_color", Color.WHITE)
		_label.add_theme_color_override("font_outline_color", Color(0, 0, 0))
		_label.add_theme_constant_override("outline_size", 3)
		_label.add_theme_font_size_override("font_size", 12)
		_label.position = Vector2(-32, -24)
		_label.size = Vector2(64, 16)
		_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		_label.mouse_filter = Control.MOUSE_FILTER_IGNORE
		add_child(_label)
	_refresh_sprite()
	_refresh_label()


func setup(data: Dictionary) -> void:
	base_data = data
	_placement = data.get("placement", {})
	_current_level = int(data.get("level", 1))
	_refresh_sprite()
	_refresh_label()


func _refresh_sprite() -> void:
	if _sprite == null:
		return
	var tier: int = _current_level
	var base_data_dict: Dictionary = _load_base_data()
	var upgrades: Array = base_data_dict.get("upgrades", [])
	if tier < 1 or tier > upgrades.size():
		_sprite.texture = null
		return
	var sprite_base: String = str(upgrades[tier - 1].get("sprite_base", "base_t" + str(tier)))
	var path := "res://assets/sprites/base/%s.png" % sprite_base
	if ResourceLoader.exists(path):
		var tex := load(path) as Texture2D
		if tex != null:
			_sprite.texture = tex
			_sprite.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST


func _refresh_label() -> void:
	if _label == null:
		return
	var base_data_dict: Dictionary = _load_base_data()
	var upgrades: Array = base_data_dict.get("upgrades", [])
	if _current_level < 1 or _current_level > upgrades.size():
		_label.text = "Base (L?)"
		return
	var name: String = str(upgrades[_current_level - 1].get("name", "Base"))
	_label.text = "%s (L%d)" % [name, _current_level]


func _load_base_data() -> Dictionary:
	var path := "res://data/base.json"
	if not ResourceLoader.exists(path):
		return {}
	var raw = load(path)
	if raw == null:
		return {}
	var data = raw.data if "data" in raw else raw
	if not (data is Dictionary):
		return {}
	return data


func get_cell(cell_size: int = 64) -> Vector2i:
	if has_meta("cell"):
		return get_meta("cell") as Vector2i
	var _cs := cell_size
	return Vector2i(
		int(floor(global_position.x / float(_cs))),
		int(floor(global_position.y / float(_cs))),
	)


func get_size_cells() -> Vector2i:
	var tier: int = _current_level
	var base_data_dict: Dictionary = _load_base_data()
	var upgrades: Array = base_data_dict.get("upgrades", [])
	if tier < 1 or tier > upgrades.size():
		return Vector2i(4, 4)
	return Vector2i(int(upgrades[tier - 1].get("size_tiles", [4, 4])[0]), int(upgrades[tier - 1].get("size_tiles", [4, 4])[1]))
