#!/usr/bin/env python3
"""Generate floor pickup sprites (stick, stone) via PIL.

Saves 12x12 PNGs to assets/sprites/floor_pickups/{item_id}.png. Small,
low-detail — these are the lowest-tier items in the game and the player
will see them everywhere.

Idempotent: skips existing files. Use --force to overwrite.
"""

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "assets" / "sprites" / "floor_pickups"
GDFILE = OUT_DIR / ".gdignore"

CELL = 12


def render_stick(draw: ImageDraw.ImageDraw) -> None:
    # A diagonal brown stick: 8-pixel line at 30 degrees
    draw.line([(2, 9), (9, 2)], fill=(110, 80, 50), width=2)
    draw.line([(2, 9), (9, 2)], fill=(70, 50, 30), width=1)


def render_stone(draw: ImageDraw.ImageDraw) -> None:
    # A small grey rock
    draw.ellipse([2, 3, 9, 10], fill=(140, 140, 140), outline=(40, 40, 40))
    draw.point((4, 5), fill=(200, 200, 200))


RENDERERS = {
    "stick": render_stick,
    "stone": render_stone,
}


def render(item_id: str, force: bool) -> str:
    out_path = OUT_DIR / f"{item_id}.png"
    if out_path.exists() and not force:
        return "skip"
    fn = RENDERERS.get(item_id)
    if fn == None:
        return f"fail: no renderer for {item_id}"
    img = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    fn(draw)
    img.save(out_path, "PNG")
    return "ok"


def write_gdignore() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if not GDFILE.exists():
        GDFILE.write_text("# generated by tools/generate_floor_pickups.py\n")


def remove_gdignore() -> None:
    if GDFILE.exists():
        GDFILE.unlink()


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--force", action="store_true")
    args = p.parse_args()

    print(f"Rendering {len(RENDERERS)} floor pickup sprites...")
    write_gdignore()
    try:
        ok = skip = fail = 0
        for item_id, fn in RENDERERS.items():
            status = render(item_id, args.force)
            if status == "ok":
                ok += 1
                print(f"  ok   {item_id}.png")
            elif status == "skip":
                skip += 1
            else:
                fail += 1
                print(f"  FAIL {item_id}: {status}")
        print(f"Done. ok={ok} skip={skip} fail={fail}")
        return 0 if fail == 0 else 2
    finally:
        remove_gdignore()


if __name__ == "__main__":
    sys.exit(main())
