#!/usr/bin/env python3
## Procedural station sprite generator.
##
## v0.6.0 follow-up polish. Produces 24x24 PNGs for each craftable
## station. Stations are placeable structures on the local map that
## the player can interact with (open UI, craft, etc.).
##
## Output:
##   assets/sprites/stations/<station_id>.png  (24x24 RGBA, NEAREST)
##   assets/sprites/stations/_generic.png      (fallback)

import json
import sys
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "assets" / "sprites" / "stations"
GDFILE = OUT_DIR / ".gdignore"

CELL = 24

# Per-station visual config. (top_color, accent_color, label)
STATION_STYLES = {
	"cooking_table": {
		"top":    (160, 100, 50),    # warm wood
		"base":   (90, 50, 25),      # dark wood
		"flame":  (240, 140, 30),    # orange flame
	},
}


def _draw_station(draw, station_id: str) -> None:
	style = STATION_STYLES.get(station_id, {
		"top":   (140, 140, 140),
		"base":  (80, 80, 80),
		"flame": (200, 80, 30),
	})
	top = style["top"]
	base = style["base"]
	flame = style["flame"]
	outline = (max(0, base[0] - 30), max(0, base[1] - 30), max(0, base[2] - 30))

	# Table top (horizontal bar across the cell)
	draw.rectangle([2, 8, CELL - 3, 14], fill=top, outline=outline)
	# Legs
	draw.rectangle([4, 14, 7, CELL - 3], fill=base, outline=outline)
	draw.rectangle([CELL - 8, 14, CELL - 5, CELL - 3], fill=base, outline=outline)
	# Pot / cauldron on top
	draw.ellipse([7, 2, CELL - 8, 11], fill=base, outline=outline)
	# Flame inside the pot
	draw.polygon([(11, 9), (12, 5), (13, 8), (14, 5), (15, 9)],
				 fill=flame, outline=outline)
	# Tiny steam wisp
	draw.line([(11, 2), (11, 4)], fill=outline, width=1)
	draw.line([(14, 1), (14, 4)], fill=outline, width=1)


def _draw_generic(draw) -> None:
	# Generic crate/box icon (used as fallback when no specific sprite exists)
	draw.rectangle([3, 8, CELL - 4, CELL - 4], fill=(120, 100, 80), outline=(60, 40, 20))
	draw.line([(3, 12), (CELL - 4, 12)], fill=(80, 60, 40), width=1)
	draw.line([(3, 16), (CELL - 4, 16)], fill=(80, 60, 40), width=1)


def main() -> int:
	OUT_DIR.mkdir(parents=True, exist_ok=True)
	if not GDFILE.exists():
		GDFILE.write_text("# generated by tools/generate_station_sprites.py\n")
	ok = 0
	for station_id in STATION_STYLES:
		img = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
		draw = ImageDraw.Draw(img)
		_draw_station(draw, station_id)
		out_path = OUT_DIR / f"{station_id}.png"
		img.save(out_path, "PNG")
		ok += 1
	# Generic fallback
	img = Image.new("RGBA", (CELL, CELL), (0, 0, 0, 0))
	draw = ImageDraw.Draw(img)
	_draw_generic(draw)
	img.save(OUT_DIR / "_generic.png", "PNG")
	ok += 1
	print(f"Done. ok={ok} ({len(STATION_STYLES)} stations + generic)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
